# Generated from the provider's pinned SQLite source fixture.
# Edit the generator inputs, then regenerate; do not edit this file by hand.

entity "authors" {
  key = ["au_id"]

  property "au_id" {
    required = true
    type = "string"
  }

  property "au_lname" {
    required = true
    type = "string"
  }

  property "au_fname" {
    required = true
    type = "string"
  }

  property "phone" {
    required = true
    type = "string"
  }

  property "address" {
    type = "string"
  }

  property "city" {
    type = "string"
  }

  property "state" {
    type = "string"
  }

  property "zip" {
    type = "string"
  }

  property "contract" {
    required = true
    type = "int"
  }
}

entity "discounts" {

  property "discounttype" {
    required = true
    type = "string"
  }

  property "stor_id" {
    entity = "stores"
  }

  property "lowqty" {
    type = "int"
  }

  property "highqty" {
    type = "int"
  }

  property "discount" {
    required = true
    type = "decimal"
  }
}

entity "employee" {
  key = ["emp_id"]

  property "emp_id" {
    required = true
    type = "string"
  }

  property "fname" {
    required = true
    type = "string"
  }

  property "minit" {
    type = "string"
  }

  property "lname" {
    required = true
    type = "string"
  }

  property "job_id" {
    required = true
    entity = "jobs"
  }

  property "job_lvl" {
    type = "int"
  }

  property "pub_id" {
    required = true
    entity = "publishers"
  }

  property "hire_date" {
    required = true
    type = "string"
  }
}

entity "jobs" {
  key = ["job_id"]

  property "job_id" {
    required = true
    type = "int"
  }

  property "job_desc" {
    required = true
    type = "string"
  }

  property "min_lvl" {
    required = true
    type = "int"
  }

  property "max_lvl" {
    required = true
    type = "int"
  }
}

entity "pub_info" {
  key = ["pub_id"]

  property "pub_id" {
    required = true
    entity = "publishers"
  }

  property "logo" {
    type = "document"
  }

  property "pr_info" {
    type = "string"
  }
}

entity "publishers" {
  key = ["pub_id"]

  property "pub_id" {
    required = true
    type = "string"
  }

  property "pub_name" {
    type = "string"
  }

  property "city" {
    type = "string"
  }

  property "state" {
    type = "string"
  }

  property "country" {
    type = "string"
  }
}

entity "roysched" {

  property "title_id" {
    entity = "titles"
  }

  property "lorange" {
    type = "int"
  }

  property "hirange" {
    type = "int"
  }

  property "royalty" {
    type = "int"
  }
}

entity "sales" {
  key = ["stor_id","ord_num","title_id"]

  property "stor_id" {
    required = true
    entity = "stores"
  }

  property "ord_num" {
    required = true
    type = "string"
  }

  property "ord_date" {
    required = true
    type = "string"
  }

  property "qty" {
    required = true
    type = "int"
  }

  property "payterms" {
    required = true
    type = "string"
  }

  property "title_id" {
    required = true
    entity = "titles"
  }
}

entity "stores" {
  key = ["stor_id"]

  property "stor_id" {
    required = true
    type = "string"
  }

  property "stor_name" {
    type = "string"
  }

  property "stor_address" {
    type = "string"
  }

  property "city" {
    type = "string"
  }

  property "state" {
    type = "string"
  }

  property "zip" {
    type = "string"
  }
}

entity "titleauthor" {
  key = ["au_id","title_id"]

  property "au_id" {
    required = true
    entity = "authors"
  }

  property "title_id" {
    required = true
    entity = "titles"
  }

  property "au_ord" {
    type = "int"
  }

  property "royaltyper" {
    type = "int"
  }
}

entity "titles" {
  key = ["title_id"]

  property "title_id" {
    required = true
    type = "string"
  }

  property "title" {
    required = true
    type = "string"
  }

  property "type" {
    required = true
    type = "string"
  }

  property "pub_id" {
    entity = "publishers"
  }

  property "price" {
    type = "decimal"
  }

  property "advance" {
    type = "decimal"
  }

  property "royalty" {
    type = "int"
  }

  property "ytd_sales" {
    type = "int"
  }

  property "notes" {
    type = "string"
  }

  property "pubdate" {
    required = true
    type = "string"
  }
}
